<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Lastream.Lastfm</PackageId>
    <VersionPrefix>1.0.1</VersionPrefix> <!-- https://stackoverflow.com/a/42615574/268555 -->

    <Title>Lastream Last.fm SDK</Title>
    <Description>Last.fm SDK for modern .NET platforms. Maintained fork of Inflatable.Lastfm.</Description>
    <Authors>kapral</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/kapral/lastfm</PackageProjectUrl>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageTags>lastfm last.fm sdk api music metadata scrobble scrobbling portable netstandard</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>netstandard1.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Net.Http" Version="4.3.2" />
    <PackageReference Include="Newtonsoft.Json" Version="9.0.1" />
  </ItemGroup>

</Project>
